[phases.install]
cmds = ["pnpm install --frozen-lockfile=false"]

[phases.build]
cmds = [
  "ls -la /app", 
  "ls -la /app/server || echo 'server dir not found'",
  "pnpm run build:client",
  "pnpm run build:server"
]

[start]
cmd = "node dist/server/node-build.mjs"
